version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: master  
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
